apiVersion: v1
kind: Pod
metadata:
  name: labeltest
  labels:
    runnings: afterLabels
  namespace: default
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - sleep
      - "60"
  restartPolicy: Always
