apiVersion: v1
kind: Pod
metadata:
  name: pod-academy
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - env
    env:
    - name: STUDENT_NAME
      valueFrom:
        configMapKeyRef:
          name: school-config
          key: STUDENT_NAME
    - name: SCHOOL
      valueFrom:
        configMapKeyRef:
          name: school-config
          key: SCHOOL
    - name: KUBENETES
      valueFrom:
        configMapKeyRef:
          name: school-config
          key: KUBENETES
   restartPolicy: Never
